# Generated by Django 6.0 on 2026-02-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
