# Generated by Django 6.0 on 2026-03-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_stocktransferlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
