# Generated by Django 6.0 on 2026-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_stocktransferlog_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_eligible_blue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_eligible_pink',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_eligible_white',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_eligible_yellow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ration_card_color',
            field=models.CharField(choices=[('yellow', 'Yellow (AAY)'), ('pink', 'Pink (PHH)'), ('blue', 'Blue (NPS)'), ('white', 'White (NPNS)')], default='white', max_length=10),
        ),
    ]
