# Generated by Django 6.0 on 2026-03-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_staff_alter_profile_role_alter_profile_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
