# Generated by Django 6.0 on 2026-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_profile_city_profile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subsidy',
            field=models.BooleanField(default=False),
        ),
    ]
