# Generated by Django 6.0 on 2026-03-17 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_purchaseorder_supplier_purchaseorderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='e.g. Vehicle No., Challan No., Source Office', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending – Awaiting Confirmation'), ('Confirmed', 'Confirmed – Stock Updated'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='mainapp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockArrivalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.stockarrival')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
        ),
    ]
