# Generated by Django 6.0 on 2026-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockarrival',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockarrival',
            name='expected_arrival',
            field=models.DateTimeField(blank=True, help_text='Scheduled arrival time for the load', null=True),
        ),
        migrations.AddField(
            model_name='stockarrival',
            name='vehicle_no',
            field=models.CharField(blank=True, help_text='Transport vehicle number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockarrival',
            name='notes',
            field=models.TextField(blank=True, help_text='e.g. Challan No., Source Office', null=True),
        ),
    ]
