# Generated by Django 6.0 on 2026-03-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_stockarrival_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferlog',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferlog',
            name='vehicle_no',
            field=models.CharField(blank=True, help_text='Vehicle carrying the transferred stock', max_length=20, null=True),
        ),
    ]
